"""change shiftparticipant to reference shelter member

Revision ID: 06edd51fb5ab
Revises: 6eb547981598
Create Date: 2026-05-12 16:35:31.191885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06edd51fb5ab'
down_revision: Union[str, Sequence[str], None] = '6eb547981598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("shift_participant")}

    if "member_id" in columns or "volunteer_id" not in columns:
        return

    with op.batch_alter_table('shift_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_shift_participant_volunteer_id_volunteer'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_shift_participant_member_id_shelter_member'), 'shelter_member', ['member_id'], ['id'])
        batch_op.drop_column('volunteer_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volunteer_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_shift_participant_member_id_shelter_member'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_shift_participant_volunteer_id_volunteer'), 'volunteer', ['volunteer_id'], ['id'])
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
