"""initial

Revision ID: 13c41c5f4b9c
Revises: 
Create Date: 2026-03-22 13:13:54.752536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c41c5f4b9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_id'), ['id'], unique=False)

    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('volunteer_code', sa.String(), nullable=False),
    sa.Column('manager_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_code'),
    sa.UniqueConstraint('volunteer_code')
    )
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelter_id'), ['id'], unique=False)

    op.create_table('refuge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refuge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refuge_id'), ['id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('num_people', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_id'), ['id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name_1', sa.String(), nullable=False),
    sa.Column('last_name_2', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['login.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('animal_type', sa.Enum('CAT', 'DOG', name='animaltypeenum'), nullable=False),
    sa.Column('in_adoption', sa.Boolean(), nullable=False),
    sa.Column('refuge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['refuge_id'], ['refuge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_id'), ['id'], unique=False)

    op.create_table('shelter_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('VOLUNTEER', 'MANAGER', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_shelter_member_user_id')
    )
    with op.batch_alter_table('shelter_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelter_member_id'), ['id'], unique=False)

    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('refuge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['refuge_id'], ['refuge.id'], ),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_id'), ['id'], unique=False)

    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['shelter_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_worked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['shelter_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_participant_id'), ['id'], unique=False)

    op.create_table('shift_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'CANCELLED', 'NOT_COMPLETED', name='taskstatusenum'), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['shift_participant.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_task_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_task_id'))

    op.drop_table('shift_task')
    with op.batch_alter_table('shift_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_participant_id'))

    op.drop_table('shift_participant')
    op.drop_table('volunteer')
    op.drop_table('manager')
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_id'))

    op.drop_table('shift')
    with op.batch_alter_table('shelter_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelter_member_id'))

    op.drop_table('shelter_member')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_id'))

    op.drop_table('animal')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_id'))

    op.drop_table('task')
    with op.batch_alter_table('refuge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refuge_id'))

    op.drop_table('refuge')
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelter_id'))

    op.drop_table('shelter')
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_id'))
        batch_op.drop_index(batch_op.f('ix_login_email'))

    op.drop_table('login')
    # ### end Alembic commands ###
