"""add province table

Revision ID: 5bd384d525d0
Revises: 13c41c5f4b9c
Create Date: 2026-03-24 19:19:13.665619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd384d525d0'
down_revision: Union[str, Sequence[str], None] = '13c41c5f4b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('community_code', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provinces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provinces_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provinces_name'))
        batch_op.drop_index(batch_op.f('ix_provinces_id'))

    op.drop_table('provinces')
    # ### end Alembic commands ###
