"""initial

Revision ID: 6d4f198797ad
Revises: 
Create Date: 2026-03-14 13:43:30.101717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4f198797ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_id'), 'animal', ['id'], unique=False)
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_email'), 'login', ['email'], unique=True)
    op.create_index(op.f('ix_login_id'), 'login', ['id'], unique=False)
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('volunteer_code', sa.String(), nullable=False),
    sa.Column('manager_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_code'),
    sa.UniqueConstraint('volunteer_code')
    )
    op.create_index(op.f('ix_shelter_id'), 'shelter', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name_1', sa.String(), nullable=False),
    sa.Column('last_name_2', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['login.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('shelter_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('VOLUNTEER', 'MANAGER', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_shelter_member_user_id')
    )
    op.create_index(op.f('ix_shelter_member_id'), 'shelter_member', ['id'], unique=False)
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['shelter_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_worked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['shelter_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer')
    op.drop_table('manager')
    op.drop_index(op.f('ix_shelter_member_id'), table_name='shelter_member')
    op.drop_table('shelter_member')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_shelter_id'), table_name='shelter')
    op.drop_table('shelter')
    op.drop_index(op.f('ix_login_id'), table_name='login')
    op.drop_index(op.f('ix_login_email'), table_name='login')
    op.drop_table('login')
    op.drop_index(op.f('ix_animal_id'), table_name='animal')
    op.drop_table('animal')
    # ### end Alembic commands ###
