"""add max participants to shift

Revision ID: 6eb547981598
Revises: e1a862cb1061
Create Date: 2026-05-06 21:11:49.440327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb547981598'
down_revision: Union[str, Sequence[str], None] = 'e1a862cb1061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    shift_columns = {column["name"] for column in inspector.get_columns("shift")}

    if "max_participants" not in shift_columns:
        with op.batch_alter_table('shift', schema=None) as batch_op:
            batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_column('max_participants')

    # ### end Alembic commands ###
