"""initial

Revision ID: c0725a976e10
Revises: 
Create Date: 2026-04-20 20:11:29.412755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0725a976e10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoptant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adoptant')),
    sa.UniqueConstraint('email', name=op.f('uq_adoptant_email'))
    )
    with op.batch_alter_table('adoptant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adoptant_id'), ['id'], unique=False)

    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login'))
    )
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_id'), ['id'], unique=False)

    op.create_table('provinces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('community_code', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provinces'))
    )
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provinces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provinces_name'), ['name'], unique=True)

    op.create_table('magic_link_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adoptant_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adoptant_id'], ['adoptant.id'], name=op.f('fk_magic_link_token_adoptant_id_adoptant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_magic_link_token'))
    )
    with op.batch_alter_table('magic_link_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_link_token_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_magic_link_token_token'), ['token'], unique=True)

    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('province_id', sa.String(), nullable=False),
    sa.Column('volunteer_code', sa.String(), nullable=False),
    sa.Column('manager_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_shelter_province_id_provinces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelter')),
    sa.UniqueConstraint('manager_code', name=op.f('uq_shelter_manager_code')),
    sa.UniqueConstraint('volunteer_code', name=op.f('uq_shelter_volunteer_code'))
    )
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelter_id'), ['id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name_1', sa.String(), nullable=False),
    sa.Column('last_name_2', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['login.id'], name=op.f('fk_user_login_id_login')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('login_id', name=op.f('uq_user_login_id'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], name=op.f('fk_medicine_shelter_id_shelter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicine')),
    sa.UniqueConstraint('name', 'shelter_id', name='uq_medicine_name_shelter')
    )
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_id'), ['id'], unique=False)

    op.create_table('refuge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('province_id', sa.String(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_refuge_province_id_provinces')),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], name=op.f('fk_refuge_shelter_id_shelter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refuge'))
    )
    with op.batch_alter_table('refuge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refuge_id'), ['id'], unique=False)

    op.create_table('shelter_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('VOLUNTEER', 'MANAGER', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], name=op.f('fk_shelter_member_shelter_id_shelter')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_shelter_member_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelter_member')),
    sa.UniqueConstraint('user_id', name='uq_shelter_member_user_id')
    )
    with op.batch_alter_table('shelter_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelter_member_id'), ['id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('num_people', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], name=op.f('fk_task_shelter_id_shelter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_id'), ['id'], unique=False)

    op.create_table('trait',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], name=op.f('fk_trait_shelter_id_shelter'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trait'))
    )
    with op.batch_alter_table('trait', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trait_id'), ['id'], unique=False)

    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('animal_type', sa.Enum('CAT', 'DOG', name='animaltypeenum'), nullable=False),
    sa.Column('in_adoption', sa.Boolean(), nullable=False),
    sa.Column('refuge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['refuge_id'], ['refuge.id'], name=op.f('fk_animal_refuge_id_refuge')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal'))
    )
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_id'), ['id'], unique=False)

    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['shelter_member.id'], name=op.f('fk_manager_id_shelter_member')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager'))
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.Column('refuge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['refuge_id'], ['refuge.id'], name=op.f('fk_shift_refuge_id_refuge')),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelter.id'], name=op.f('fk_shift_shelter_id_shelter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift'))
    )
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_id'), ['id'], unique=False)

    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_worked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['shelter_member.id'], name=op.f('fk_volunteer_id_shelter_member')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer'))
    )
    op.create_table('adoption_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('adoptant_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'REJECTED', name='adoptionprocessstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['adoptant_id'], ['adoptant.id'], name=op.f('fk_adoption_process_adoptant_id_adoptant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_adoption_process_animal_id_animal'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adoption_process'))
    )
    with op.batch_alter_table('adoption_process', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adoption_process_id'), ['id'], unique=False)

    op.create_table('animal_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_animal_image_animal_id_animal'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_image'))
    )
    with op.batch_alter_table('animal_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_image_id'), ['id'], unique=False)

    op.create_table('animal_trait',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_animal_trait_animal_id_animal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_id'], ['trait.id'], name=op.f('fk_animal_trait_trait_id_trait'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('animal_id', 'trait_id', name=op.f('pk_animal_trait'))
    )
    op.create_table('animal_treatment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'AS_NEEDED', name='medicinefrequencyenum'), nullable=False),
    sa.Column('status', sa.Enum('GIVEN', 'PENDING', name='medicinestatusenum'), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('dosage', sa.Float(), nullable=False),
    sa.Column('dosage_unit', sa.Enum('MG', 'ML', 'DROPS', 'UNITS', name='dosageunitenum'), nullable=False),
    sa.Column('status_last_updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_animal_treatment_animal_id_animal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine.id'], name=op.f('fk_animal_treatment_medicine_id_medicine'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_last_updated_by_id'], ['user.id'], name=op.f('fk_animal_treatment_status_last_updated_by_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_treatment'))
    )
    with op.batch_alter_table('animal_treatment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_treatment_id'), ['id'], unique=False)

    op.create_table('shift_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('fk_shift_participant_shift_id_shift')),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], name=op.f('fk_shift_participant_volunteer_id_volunteer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_participant'))
    )
    with op.batch_alter_table('shift_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_participant_id'), ['id'], unique=False)

    op.create_table('vet_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_type', sa.Enum('GENERAL_CHECKUP', 'VACCINE', 'SURGERY', 'DENTAL', 'EMERGENCY', 'OTHER', name='vetvisittypeenum'), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_vet_visit_animal_id_animal'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vet_visit'))
    )
    with op.batch_alter_table('vet_visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vet_visit_id'), ['id'], unique=False)

    op.create_table('adoption_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adoption_process_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FORM', 'INTERVIEW', 'SHELTER_VISIT', 'CONTRACT', 'ANIMAL_PICKUP', name='steptypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REJECTED', name='stepstatusenum'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['adoption_process_id'], ['adoption_process.id'], name=op.f('fk_adoption_step_adoption_process_id_adoption_process'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adoption_step'))
    )
    with op.batch_alter_table('adoption_step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adoption_step_id'), ['id'], unique=False)

    op.create_table('shift_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'CANCELLED', 'NOT_COMPLETED', name='taskstatusenum'), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_shift_task_animal_id_animal')),
    sa.ForeignKeyConstraint(['participant_id'], ['shift_participant.id'], name=op.f('fk_shift_task_participant_id_shift_participant')),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('fk_shift_task_shift_id_shift')),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_shift_task_task_id_task')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_task'))
    )
    with op.batch_alter_table('shift_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_task_id'), ['id'], unique=False)

    op.create_table('adoption_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('housing_type', sa.String(), nullable=True),
    sa.Column('has_garden', sa.Boolean(), nullable=True),
    sa.Column('has_other_pets', sa.Boolean(), nullable=True),
    sa.Column('other_pets_description', sa.String(), nullable=True),
    sa.Column('has_children', sa.Boolean(), nullable=True),
    sa.Column('children_ages', sa.String(), nullable=True),
    sa.Column('previous_pet_experience', sa.Boolean(), nullable=True),
    sa.Column('hours_alone_per_day', sa.Integer(), nullable=True),
    sa.Column('reason_for_adoption', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['adoption_step.id'], name=op.f('fk_adoption_form_id_adoption_step'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adoption_form'))
    )
    op.create_table('animal_pickup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('actual_pickup_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['adoption_step.id'], name=op.f('fk_animal_pickup_id_adoption_step'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_pickup'))
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_url', sa.String(), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(), nullable=True),
    sa.Column('generation_date', sa.Date(), nullable=True),
    sa.Column('signed_by_adoptant', sa.Boolean(), nullable=False),
    sa.Column('signed_by_shelter', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['adoption_step.id'], name=op.f('fk_contract_id_adoption_step'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract'))
    )
    op.create_table('interview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['adoption_step.id'], name=op.f('fk_interview_id_adoption_step'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview'))
    )
    op.create_table('shelter_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['adoption_step.id'], name=op.f('fk_shelter_visit_id_adoption_step'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shelter_visit'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelter_visit')
    op.drop_table('interview')
    op.drop_table('contract')
    op.drop_table('animal_pickup')
    op.drop_table('adoption_form')
    with op.batch_alter_table('shift_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_task_id'))

    op.drop_table('shift_task')
    with op.batch_alter_table('adoption_step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adoption_step_id'))

    op.drop_table('adoption_step')
    with op.batch_alter_table('vet_visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vet_visit_id'))

    op.drop_table('vet_visit')
    with op.batch_alter_table('shift_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_participant_id'))

    op.drop_table('shift_participant')
    with op.batch_alter_table('animal_treatment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_treatment_id'))

    op.drop_table('animal_treatment')
    op.drop_table('animal_trait')
    with op.batch_alter_table('animal_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_image_id'))

    op.drop_table('animal_image')
    with op.batch_alter_table('adoption_process', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adoption_process_id'))

    op.drop_table('adoption_process')
    op.drop_table('volunteer')
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_id'))

    op.drop_table('shift')
    op.drop_table('manager')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_id'))

    op.drop_table('animal')
    with op.batch_alter_table('trait', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trait_id'))

    op.drop_table('trait')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_id'))

    op.drop_table('task')
    with op.batch_alter_table('shelter_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelter_member_id'))

    op.drop_table('shelter_member')
    with op.batch_alter_table('refuge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refuge_id'))

    op.drop_table('refuge')
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_id'))

    op.drop_table('medicine')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelter_id'))

    op.drop_table('shelter')
    with op.batch_alter_table('magic_link_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_link_token_token'))
        batch_op.drop_index(batch_op.f('ix_magic_link_token_id'))

    op.drop_table('magic_link_token')
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provinces_name'))
        batch_op.drop_index(batch_op.f('ix_provinces_id'))

    op.drop_table('provinces')
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_id'))
        batch_op.drop_index(batch_op.f('ix_login_email'))

    op.drop_table('login')
    with op.batch_alter_table('adoptant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adoptant_id'))

    op.drop_table('adoptant')
    # ### end Alembic commands ###
