"""add email to shelter

Revision ID: e1a862cb1061
Revises: c0725a976e10
Create Date: 2026-05-05 18:29:07.618748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a862cb1061'
down_revision: Union[str, Sequence[str], None] = 'c0725a976e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    shelter_columns = {column["name"] for column in inspector.get_columns("shelter")}

    if bind.dialect.name == "sqlite":
        with op.batch_alter_table('animal', schema=None) as batch_op:
            batch_op.alter_column('animal_type',
                   existing_type=sa.VARCHAR(length=3),
                   type_=sa.Enum('CAT', 'DOG', 'OTHER', name='animaltypeenum'),
                   existing_nullable=False)

    if "email" not in shelter_columns:
        with op.batch_alter_table('shelter', schema=None) as batch_op:
            batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
            batch_op.create_unique_constraint(batch_op.f('uq_shelter_email'), ['email'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_shelter_email'), type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('animal_type',
               existing_type=sa.Enum('CAT', 'DOG', 'OTHER', name='animaltypeenum'),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###
