name: Scheduled URL Ping

on:
  schedule:
    #runs every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Target URL
        env:
          TARGET_URL: ${{ vars.BASTET_SERVER_URL }}
        run: |
          if [ -z "$TARGET_URL" ]; then
            echo "Error: BASTET_SERVER_URL variable is empty or not set."
            exit 1
          fi
          echo "Target URL: $TARGET_URL"
          echo "Pinging URL..."
          curl -fsS --max-time 30 "$TARGET_URL" -o /dev/null -w "HTTP status: %{http_code}\n"
